[dependencies]
etherparse = '0.8.0'
interfaces = '0.0.4'
num-complex = '0.2.1'
num-traits = '0.2.8'
pnet = '0.22.0'
serde_yaml = '0.8.8'
chrono = '0.4.7'

[dependencies.astroalgo]
path="../astroalgo"

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'controller_rs'
version = '0.1.0'
